const press = [
  [
    'Title',
    'Publication',
    'Date',
    'Author',
    'Type',
    'URL',
    'Project(s) / keywords ',
  ],
  [
    'How a Portland nonprofit is using artificial intelligence to help save whales, giraffes, zebras',
    'The Seattle Times',
    '2020-02-29',
    'Aimee Rawlins',
    'article',
    'https://www.seattletimes.com/seattle-news/environment/how-a-portland-nonprofit-is-using-artificial-intelligence-to-help-save-whales-giraffes-zebras/',
    'wildbook, ai ',
  ],
  [
    'The battle against wildlife poachers is increasingly high-tech',
    'Al Jazeera',
    '2019-09-11',
    'Lucy Sheriff',
    'article',
    'https://www.aljazeera.com/ajimpact/battle-wildlife-poachers-increasingly-high-tech-190911144002627.html',
    ' ',
  ],
  [
    'Artificial intelligence adds value in the Wild',
    'ITWeb (South Africa)',
    '2019-07-09',
    'Jessie Rudd',
    'article',
    'https://www.itweb.co.za/content/Gb3Bw7Wo6p472k6V',
    ' ',
  ],
  [
    "GiraffeSpotter: Using Big Data and Citizen Science to Protect the World's Tallest Mammals",
    'Reset (German)',
    '2019-06-24',
    'Jasmina Schmidt',
    'article',
    'https://en.reset.org/blog/giraffespotter-using-big-data-and-citizen-science-protect-worlds-tallest-mammals-06242019',
    ' ',
  ],
  [
    'The Curated Wild',
    'Anthropocene Magazine',
    '2019-06-01',
    'David Biello',
    'article',
    'http://www.anthropocenemagazine.org/2019/06/the-curated-wild/',
    ' ',
  ],
  [
    'AI could be a critical tool to saving the planet',
    'The Guardian',
    '2019-04-30',
    '',
    '',
    'https://www.theguardian.com/ai-for-earth/2019/apr/30/ai-tech-sustainable-planet',
    'Wildbook ',
  ],
  [
    'Fast Company World Changing Ideas Awards 2019 Honorable Mention',
    'Fast Company',
    '2019-04-08',
    '',
    'article',
    'https://www.fastcompany.com/90329244/world-changing-ideas-2019-all-the-winners-finalists-and-honorable-mentions',
    'wildbook ',
  ],
  [
    'How Advanced Technology Can Help Save Wildlife, And The Companies Behind Them',
    'nasdaq',
    '2019-03-18',
    'Prableen Bajpai',
    'article',
    'https://www.nasdaq.com/article/how-advanced-technology-can-help-save-wildlife-and-the-companies-behind-them-cm1116142',
    ' ',
  ],
  [
    'AI empowers conservation biology',
    'Nature',
    '2019-03-04',
    'Roberta Kwok',
    'article',
    'https://www.nature.com/articles/d41586-019-00746-1?fbclid=IwAR2FZZkMqX4iGmH5vgRcdcIWtD0tQjJ6y46O0C3dos2aMG8jAY317nMZeQo',
    'wildbook ',
  ],
  [
    'Wildbook: Finding Elephants in the Data (and Whale sharks, Turtles and More, Too!)',
    'Medium',
    '2019-02-19',
    'J.A. Ginsburg',
    'article',
    'https://medium.com/@trackernews/wildbook-finding-elephants-in-the-data-and-whale-sharks-turtles-and-more-too-a40abaada67c?fbclid=IwAR3aS2XntuTQ6PjlC4WuS2IXv3z9gObkTNLU7bmarVcWYkYojGqoPskBj2Y',
    'wildbook ',
  ],
  [
    'Fighting extinction with Microsoft AI and citizen science',
    'YouTube',
    '2019-02-11',
    'Microsoft',
    'video',
    'https://www.youtube.com/watch?v=rQqao37u1wU',
    'wildbook ',
  ],
  [
    'How Microsoft is using AI to help the Earth (Practical AI #29)',
    'Practical AI (podcast)',
    '2019-02-04',
    'Chris Benson',
    'podcast',
    'https://changelog.com/practicalai/29',
    ' ',
  ],
  [
    'How Eavesdropping on Elephants is Keeping Them Safe',
    'BBC',
    '2019-01-31',
    'Rachel Nuwer',
    'article',
    'http://www.bbc.com/future/story/20190130-how-eavesdropping-on-elephants-is-keeping-them-safe',
    'Vulcan project ',
  ],
  [
    'How artificial intelligence is changing wildlife research',
    'National Geographic',
    '2018-11-13',
    'Anne Casselman',
    'article',
    'https://www.nationalgeographic.com/animals/2018/11/artificial-intelligence-counts-wild-animals/',
    'wildbook ',
  ],
  [
    'How many elephants are there?',
    'Vulcan (blog)',
    '2018-11-12',
    'Pooja M., Kathleen G.',
    'article',
    'http://engineering.vulcan.com/2018_1112_How-many-elephants-are-there.aspx',
    'Vulcan project ',
  ],
  [
    '‘Gentle giants’ urgently need conservation management',
    'Geographical',
    '2018-08-17',
    'Lucy Hodge-Sellers',
    'article',
    'https://geographical.co.uk/nature/wildlife/item/2867-whale-sharks',
    'whale shark ',
  ],
  [
    'How Conservationists Are Using AI And Big Data To Aid Wildlife',
    'OPB',
    '2018-08-14',
    'Joseph Winters',
    'article',
    'https://www.opb.org/news/article/artificial-intelligence-conservationists-portland-wildme-wildbook/',
    'wildbook ',
  ],
  [
    'H2O.ai Partners with Wildbook to Help Save Elephants with Artificial Intelligence',
    'PR Newswire',
    '2018-08-13',
    '',
    'press release',
    'https://www.prnewswire.com/news-releases/h2oai-partners-with-wildbook-to-help-save-elephants-with-artificial-intelligence-300695790.html',
    'elephants ',
  ],
  [
    'Computer Vision and Intelligent Agents for Wildlife Conservation with Jason Holmberg',
    'This Week in Machine Learning',
    '2018-07-23',
    '',
    'podcast',
    'https://twimlai.com/twiml-talk-166-computer-vision-and-intelligent-agents-for-wildlife-conservation-with-jason-holmberg/',
    'intelligent agent ',
  ],
  [
    'Astronomy Tool Helps ID Sharks',
    'Scientific American',
    '2018-07-18',
    'Annie Sneed',
    'article',
    'https://www.scientificamerican.com/podcast/episode/astronomy-tool-helps-id-sharks/',
    'whale shark ',
  ],
  [
    "New 'Facebook' for animals could help protect endangered wildlife",
    'c-net',
    '2018-07-03',
    'Bonnie Burton',
    'article',
    'https://www.cnet.com/news/new-facebook-wildbook-for-animals-could-help-protect-endangered-wildlife/',
    'wildbook ',
  ],
  [
    'Hope for endangered Grevy’s Zebra as census shows population rising',
    'Kenya Star',
    '2018-07-02',
    'Gilbert Koech',
    'article',
    'https://www.the-star.co.ke/news/2018-07-02-hope-for-endangered-grevys-zebra-as-census-shows-population-rising/',
    'wildbook ',
  ],
  [
    'The world’s animals are getting their very own Facebook',
    'Fast Company',
    '2018-06-22',
    'Jackie Snow',
    'article',
    'https://www.fastcompany.com/40585495/the-worlds-animals-are-getting-their-very-own-facebook',
    'wildbook ',
  ],
  [
    'Combating extinction one photo at a time',
    'ScienceNode',
    '2018-06-20',
    'Laura Reed',
    'article',
    'https://sciencenode.org/feature/Wildbook.php',
    'wildbook ',
  ],
  [
    'Wild Me joins AI for Earth',
    'Microsoft',
    '2018-06-14',
    '',
    'press release',
    'https://news.microsoft.com/2018/06/14/wild-me-joins-ai-for-earth/',
    ' ',
  ],
  [
    'Standing out from the pack: Wild Me uses AI to revolutionize animal identification',
    'Microsoft (blog)',
    '2018-06-14',
    'Michelle Lancaster',
    'article/blog',
    'https://blogs.microsoft.com/green/2018/06/14/standing-out-from-the-pack-wild-me-uses-ai-to-revolutionize-animal-identification/',
    ' ',
  ],
  [
    'WACV18: An Animal Detection Pipeline for Identification',
    'WACV2018 / CVF',
    '2018-03-28',
    'Jason Parham',
    'video',
    'https://www.youtube.com/watch?v=ApW1QAdsIfw',
    ' ',
  ],
  [
    'I am AI Docuseries, Episode 6: Running Wild for Nature Conservation - Wildbook',
    'NVIDIA series',
    '2018-03-28',
    '',
    'video',
    'https://www.youtube.com/watch?v=TLw_I1ghvLM',
    ' ',
  ],
  [
    'Call of the Wild(book): How GPUs Help Track Threatened Animal Species',
    'NVIDIEA blog',
    '2018-03-13',
    'Tony Kontzer',
    'article',
    'https://blogs.nvidia.com/blog/2018/03/13/wildbook-threatened-species/',
    ' ',
  ],
  [
    'The case for technology investments in the environment',
    'Nature',
    '2017-12-19',
    'Lucas Joppa',
    'article',
    'https://www.nature.com/articles/d41586-017-08675-7',
    ' ',
  ],
  [
    'Tracking the Elusive Whale Shark',
    'New York Times',
    '2017-11-29',
    'Karen Weintraub',
    'article',
    'https://www.nytimes.com/2017/11/29/science/whale-sharks.html',
    'whale shark ',
  ],
  [
    'Snap a Shark Photo and Help Save the Biggest Fish on Earth',
    'National Geographic',
    '2017-11-29',
    'Jason Bittel',
    'article',
    'https://news.nationalgeographic.com/2017/11/animals-whales-oceans-tourism-endangered/',
    ' ',
  ],
  [
    'The Citizen Science Revolution and Artificial Intelligence',
    'SciTech Connect',
    '2017-11-17',
    'Michael Bear',
    'article',
    'http://scitechconnect.elsevier.com/citizen-science-revolution-artificial-intelligence/',
    ' ',
  ],
  [
    "The Great Grevy's Rally 2018",
    'GGR',
    '2017-10-20',
    '',
    'video',
    'https://www.youtube.com/watch?v=nsiPnanLRzI',
    ' ',
  ],
  [
    'Finding Big Fish Online: How Wild Me Is Turning Vacation Videos Into Shark Science with Artificial Intelligence',
    'PR Web',
    '2017-05-18',
    '',
    'press release',
    'https://www.prweb.com/releases/2017/05/prweb14334385.htm',
    ' ',
  ],
  [
    "Tracking the Sea's Gentle Giants",
    'National Geographic',
    '2016-11-11',
    'Gary Strauss',
    'article',
    'https://news.nationalgeographic.com/2016/11/brad-norman-explorer-moments-identification-system-helps-protect-whale-sharks/',
    ' ',
  ],
  [
    '5 Intriguing Uses for Artificial Intelligence',
    'LiveScience',
    '2016-10-14',
    'Laura Geggel',
    'article',
    'https://www.livescience.com/56497-artificial-intelligence-intriguing-uses.html',
    ' ',
  ],
  [
    "Citizens and scientists earn their stripes counting Kenya's Grevy's zebras",
    'euronews',
    '2016-02-19',
    '',
    'video',
    'https://www.youtube.com/watch?v=SezjJxx6NQg',
    ' ',
  ],
  [
    'UIC Researchers are Crowd-Sourcing Wildlife Photos In Kenya to Collect Animal Data',
    'Chicago Inno',
    '2015-02-16',
    'Jim Dallke',
    'article',
    'https://www.americaninno.com/chicago/african-animals-photographed-will-help-researchers-collect-wildlife-data/',
    ' ',
  ],
  [
    'New Technology Identifies Zebras by Their Stripes',
    'Audobon',
    '2012-03-12',
    'Alisa Opar',
    'article',
    'https://www.audubon.org/news/new-technology-identifies-zebras-their-stripes',
    ' ',
  ],
  [
    'The Internet of Turtles',
    'SWOT',
    '2012-01-01',
    'Aimée Leslie et al',
    'article (pdf)',
    'http://seaturtlestatus.org/sites/swot/files/SWOT11_p12-13_Internet%20of%20Turtles.pdf',
  ],
];

export default press;
