const press = [
  [
    'Title',
    'Publication',
    'Date',
    'Author',
    'Type',
    'URL',
    'Project(s) / keywords ',
  ],
  [
    'How many elephants are there?',
    'Vulcan (blog)',
    '2018-11-12',
    'Pooja M., Kathleen G.',
    'article',
    'http://engineering.vulcan.com/2018_1112_How-many-elephants-are-there.aspx',
    'Vulcan project [Wild Me specific] ',
  ],
  [
    'Hope for endangered Grevy’s Zebra as census shows population rising',
    'Kenya Star',
    '2018-07-02',
    'Gilbert Koech',
    'article',
    'https://www.the-star.co.ke/news/2018-07-02-hope-for-endangered-grevys-zebra-as-census-shows-population-rising/',
    'wildbook ',
  ],
  [
    'I am AI Docuseries, Episode 6: Running Wild for Nature Conservation - Wildbook',
    'NVIDIA series',
    '2018-03-28',
    '',
    'video',
    'https://www.youtube.com/watch?v=TLw_I1ghvLM',
    ' ',
  ],
  [
    "The Great Grevy's Rally 2018",
    'GGR',
    '2017-10-20',
    '',
    'video',
    'https://www.youtube.com/watch?v=nsiPnanLRzI',
    ' ',
  ],
  [
    'Finding Big Fish Online: How Wild Me Is Turning Vacation Videos Into Shark Science with Artificial Intelligence',
    'PR Web',
    '2017-05-18',
    '',
    'press release',
    'https://www.prweb.com/releases/2017/05/prweb14334385.htm',
    ' ',
  ],
  [
    "Citizens and scientists earn their stripes counting Kenya's Grevy's zebras",
    'euronews',
    '2016-02-19',
    '',
    'video',
    'https://www.youtube.com/watch?v=SezjJxx6NQg',
    ' ',
  ],
  [
    'UIC Researchers are Crowd-Sourcing Wildlife Photos In Kenya to Collect Animal Data',
    'Chicago Inno',
    '2015-02-16',
    'Jim Dallke',
    'article',
    'https://www.americaninno.com/chicago/african-animals-photographed-will-help-researchers-collect-wildlife-data/',
    ' ',
  ],
  [
    'New Technology Identifies Zebras by Their Stripes',
    'Audobon',
    '2012-03-12',
    'Alisa Opar',
    'article',
    'https://www.audubon.org/news/new-technology-identifies-zebras-their-stripes',
    ' ',
  ],
];

export default press;
